# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vk_KukobaAlexander' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vk_KukobaAlexander
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'PromiseKit'
pod 'SwiftyJSON'
pod 'ReadMoreTextView'
pod 'SDWebImage' 
pod 'SwiftyJSON'
end
